services:
  php:
    build:
      dockerfile: ./docker/php.Dockerfile
      context: ./
    volumes:
      - ./:/var/www/html
    networks:
      bingo:

  httpd:
    image: httpd:alpine
    volumes:
      - ./:/var/www/html
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "8080:80"
    networks:
      bingo:

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bingo
      MYSQL_USER: bingo
      MYSQL_PASSWORD: B!ng0
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./var/data/mysql:/var/lib/mysql/
    ports:
      - "33068:3306"
    networks:
      bingo:

networks:
  bingo: