services:
  php:
    image: php:8.4-apache-trixie
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./var/log/docker:/var/log/
    networks:
      bingo:

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bingo
      MYSQL_USER: bingo
      MYSQL_PASSWORD: B!ng0
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./var/data/mysql:/var/lib/mysql/
    ports:
      - "33068:3306"
    networks:
      bingo:

networks:
  bingo: